--- 
- hosts: all
  ignore_errors: yes
  become: yes
  tasks:
     - name: create user
       user:
        name: boukoue
        comment: boukoue edith flore
     - name: create directory
       file:
          path: /tmp/devops-ans
          owner: boukoue
          state: directory
          mode: "0777"
         
     - name: create file
       file:
         path: /tmp/ansible-class
         owner: boukoue
         state: touch
         mode: "0600"


